# Generated by Django 3.2.5 on 2021-12-18 22:14

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('gas_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fillup',
            name='car',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fillups', to='gas_app.car'),
        ),
        migrations.AlterField(
            model_name='fillup',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fillups', to=settings.AUTH_USER_MODEL),
        ),
    ]
