# Generated by Django 3.2.5 on 2021-12-18 23:13

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('gas_app', '0002_auto_20211218_2214'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fillup',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
