# Generated by Django 4.0.1 on 2022-02-12 22:58

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gas_app', '0004_alter_car_model_year'),
    ]

    operations = [
        migrations.AlterField(
            model_name='car',
            name='model_year',
            field=models.IntegerField(verbose_name=django.core.validators.MaxValueValidator(2023)),
        ),
    ]
