# Generated by Django 4.0.1 on 2022-03-03 02:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gas_app', '0007_alter_car_model_year'),
    ]

    operations = [
        migrations.AddField(
            model_name='fillup',
            name='fuel_grade',
            field=models.CharField(choices=[('Regular', 'Regular'), ('Mid-grade', 'Mid-grade'), ('Premium', 'Premium'), ('Diesel', 'Diesel')], default='Regular', max_length=10),
        ),
    ]
